collections:
  authors:
    output: true
  recruitInfos:  
    output: true
  products:
    output: true
  types:
    output: true


defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "recruitInfos"
    values:
      layout: "recruitInfo"